CREATE TABLE `app_menu_config` (
  `id` int NOT NULL AUTO_INCREMENT,
  `group_name` varchar(50) NOT NULL DEFAULT '' COMMENT '分组名称',
  `group_key` varchar(50) NOT NULL DEFAULT '' COMMENT '分组标识',
  `group_sort` int NOT NULL DEFAULT 0 COMMENT '分组排序',
  `title` varchar(50) NOT NULL COMMENT '菜单标题',
  `icon` varchar(100) NOT NULL DEFAULT '' COMMENT '图标名称',
  `path` varchar(255) NOT NULL DEFAULT '' COMMENT '跳转路径',
  `icon_color` varchar(20) NOT NULL DEFAULT '#3D6DF7' COMMENT '图标颜色',
  `bg_color` varchar(20) NOT NULL DEFAULT '#E8F0FE' COMMENT '图标背景色',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '组内排序',
  `visible` tinyint NOT NULL DEFAULT 1 COMMENT '是否显示（1显示 0隐藏）',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '状态（0正常 1停用）',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='App移动端菜单配置表';

INSERT INTO `app_menu_config` (`group_name`, `group_key`, `group_sort`, `title`, `icon`, `path`, `icon_color`, `bg_color`, `sort_order`, `visible`, `status`) VALUES
('常用功能', 'quick', 1, '打卡', 'clock', '/pages/attendance/index', '#3D6DF7', '#E8F0FE', 1, 1, '0'),
('常用功能', 'quick', 1, '开单', 'file-text', '/pages/business/sales/index', '#3D6DF7', '#E8F0FE', 2, 1, '0'),
('常用功能', 'quick', 1, '行程', 'calendar', '/pages/business/schedule/index', '#3D6DF7', '#E8F0FE', 3, 1, '0'),
('常用功能', 'quick', 1, '订单', 'list', '/pages/business/order/index', '#3D6DF7', '#E8F0FE', 4, 1, '0'),
('常用功能', 'quick', 1, '个人信息', 'account-fill', '/pages/mine/info/index', '#3D6DF7', '#E8F0FE', 5, 1, '0'),
('常用功能', 'quick', 1, '修改密码', 'lock-fill', '/pages/mine/pwd/index', '#3D6DF7', '#E8F0FE', 6, 1, '0'),
('常用功能', 'quick', 1, '应用设置', 'setting', '/pages/mine/setting/index', '#3D6DF7', '#E8F0FE', 7, 1, '0'),
('常用功能', 'quick', 1, '日志查询', 'file-text', '', '#3D6DF7', '#E8F0FE', 8, 1, '0'),
('业务管理', 'business', 2, '企业管理', 'home-fill', '/pages/business/enterprise/index', '#fff', '#FF6B35', 1, 1, '0'),
('业务管理', 'business', 2, '门店管理', 'shop', '/pages/business/store/index', '#fff', '#FF6B35', 2, 1, '0'),
('业务管理', 'business', 2, '行程安排', 'calendar', '/pages/business/schedule/index', '#fff', '#FF6B35', 3, 1, '0'),
('业务管理', 'business', 2, '销售开单', 'edit-pen', '/pages/business/sales/index', '#fff', '#FF6B35', 4, 1, '0'),
('业务管理', 'business', 2, '项目操作', 'grid', '/pages/business/operation/index', '#fff', '#FF6B35', 5, 1, '0'),
('业务管理', 'business', 2, '订单管理', 'list', '/pages/business/order/index', '#fff', '#FF6B35', 6, 1, '0'),
('系统管理', 'system', 3, '用户管理', 'account', '', '#fff', '#3D6DF7', 1, 1, '0'),
('系统管理', 'system', 3, '角色管理', 'man-add', '', '#fff', '#3D6DF7', 2, 1, '0'),
('系统管理', 'system', 3, '菜单管理', 'list', '', '#fff', '#3D6DF7', 3, 1, '0'),
('系统管理', 'system', 3, '部门管理', 'home', '', '#fff', '#3D6DF7', 4, 1, '0'),
('系统管理', 'system', 3, '岗位管理', 'bookmark', '', '#fff', '#3D6DF7', 5, 1, '0'),
('系统管理', 'system', 3, '字典管理', 'file-text', '', '#fff', '#3D6DF7', 6, 1, '0'),
('系统管理', 'system', 3, '参数设置', 'setting', '', '#fff', '#3D6DF7', 7, 1, '0'),
('系统管理', 'system', 3, '通知公告', 'chat', '', '#fff', '#3D6DF7', 8, 1, '0'),
('快捷操作', 'mine_action', 4, '在线客服', 'chat', '', '#666', '#f5f5f5', 1, 1, '0'),
('快捷操作', 'mine_action', 4, '反馈社区', 'edit-pen', '', '#666', '#f5f5f5', 2, 1, '0'),
('快捷操作', 'mine_action', 4, '点赞我们', 'thumb-up', '', '#666', '#f5f5f5', 3, 1, '0'),
('快捷操作', 'mine_action', 4, '关于我们', 'info-circle', '/pages/mine/about/index', '#666', '#f5f5f5', 4, 1, '0'),
('个人菜单', 'mine_menu', 5, '编辑资料', 'edit-pen', '/pages/mine/info/edit', '#3c96f3', '#e8f2ff', 1, 1, '0'),
('个人菜单', 'mine_menu', 5, '常见问题', 'question-circle', '/pages/mine/help/index', '#3c96f3', '#e8f2ff', 2, 1, '0'),
('个人菜单', 'mine_menu', 5, '关于我们', 'info-circle', '/pages/mine/about/index', '#3c96f3', '#e8f2ff', 3, 1, '0'),
('个人菜单', 'mine_menu', 5, '应用设置', 'setting', '/pages/mine/setting/index', '#3c96f3', '#e8f2ff', 4, 1, '0');
